spring:
  profiles:
    active: dev
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: true
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
---
spring:
  server:
    scheme: http
  datasource:
    url: jdbc:mariadb://localhost:3306/kotlin_test_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: rhkfh1
    driverClassName: org.mariadb.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
  config:
    activate:
      on-profile: dev
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
spring:
  server:
    scheme: https
  datasource:
    url: jdbc:mariadb://localhost:3306/kotlin_test_prod?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: rhkfh1
    driverClassName: org.mariadb.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
  jpa:
    hibernate:
      ddl-auto: none
  config:
    activate:
      on-profile: prod